name: example
publish_to: "none"
environment:
  sdk: ^3.11.0-142.0.dev
dependencies:
  flutter:
    sdk: flutter
  inherited_value:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
