name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0-142.0.dev

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  flutter_custom_analyzers:
    path: ../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
