name: flutter_custom_analyzers
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_plugin: ^0.3.0
  
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
