name: example
publish_to: "none"
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  container2:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
